USE [DCENTER]
GO

/****** Object:  Index [M店舗KEY2]    Script Date: 2021/11/12 18:19:06 ******/
CREATE NONCLUSTERED INDEX [M店舗KEY2] ON [dbo].[M_店舗]
(
	[会社店ｺｰﾄﾞ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
