USE [DCENTER]
GO

/****** Object:  Index [NonClusteredIndex-20211112-171855]    Script Date: 2021/11/12 18:15:33 ******/
CREATE NONCLUSTERED INDEX [ncidx_F入庫受信_JANｺｰﾄﾞ] ON [dbo].[F_入庫受信]
(
	[JANｺｰﾄﾞ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
