USE [DCENTER]
GO

/****** Object:  Index [NonClusteredIndex-20211112-171821]    Script Date: 2021/11/12 18:17:46 ******/
CREATE NONCLUSTERED INDEX [ncidx_F伝票明細_JANｺｰﾄﾞ] ON [dbo].[F_伝票明細]
(
	[JANｺｰﾄﾞ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
